done task-22
AndrewHelix/react-homeworks pull request #11
Opened 2022-04-29 16:17 UTC by AndrewHelix

2022-05-05 18:22 UTC, PaulVersAtile requested changes

2022-05-05 18:22 UTC, PaulVersAtile commented on src/Task-22.tsx
> +  }
Можно сразу рассчитать как переменную

2022-05-05 18:22 UTC, PaulVersAtile commented on src/Task-22.tsx
> +  }
Попробуй сделать стейт с выбранными элементами не массивом, а объектом. В объекте гораздо проще добавлять и удалять элементы

2022-05-05 18:22 UTC, PaulVersAtile commented on src/Task-22.tsx
> +type TIngredient = {
Мода на названия типов, начинающихся с букв T, в тайпскрипте прошла. Можно просто `Ingredient`. Если же есть конфликт имен, то тогда обычно делают IngredientType / IngredientComponent, т.е. более явно

2022-05-05 20:19 UTC, AndrewHelix commented on src/Task-22.tsx
> +  }
Если ты про то, что она в памяти хранится в виде кучи, то ок, согласен. В объекте сразу по ключу получаю нужное значение, массив же в данном кейсе нужно перебирать.
Но с другой стороны, вместо того, чтобы просто взять длину стейта, мне теперь приходится делать костыль Object.keys(state).length 2 раза. Иначе как ещё проверить, сколько ингредиентов в стейте, который теперь объект
И вот тут встает вопрос: а что менее затратно - деструктурировать массив и добавить в конец 1 значение и фильтровать при удалении или же делать из ключей объекта массив 
Это если ты имел ввиду "гораздо проще добавлять и удалять элементы" про обращение с памятью. Если нет, то я тебя не понял.

Плюс такой синтаксис с вычисляемыми свойствами при деструктуризации [e.target.value]: _    попрошу объяснить. Его тупо нагуглил, но не понял почему я не могу деструктурировать просто [e.target.value], ...other ? Как это работает?

2022-05-05 20:37 UTC, AndrewHelix commented on src/Task-22.tsx
> +  }
UPD: ещё погуглил, если правильно понял, то в записи [e.target.value], ...other по сути никакой переменной нет, только вычисляемое свойство определяю какое хочу достать, но никуда его не присвоил, т.к. нет переменной
А тут  [e.target.value]: _ , ...other уже вычисляется нужное свойство объекта (напр. pepperoni) и это же не какая-то переменная, поэтому значение этого свойства помещаем в переменную _ . Что по сути эквивалентно записи state[_]  ?
Так?

2022-05-19 13:17 UTC, PaulVersAtile commented on src/Task-22.tsx
> +  }
Я думаю что в функции onChangeCheckbox достаточно просто по ключу класть значение `e.target.checked`. Ключом в этом объекте может быть название ингредиента, а значением boolean. Т.е. нет нужды заниматься иммутабельным удалением ключа из объекта

2022-05-20 09:55 UTC, PaulVersAtile approved these changes

2022-05-20 09:55 UTC, PaulVersAtile commented on src/Task-22.tsx
> +      {Object.values(selected).filter(el => el).length >= 5 && (
Вот это вычисление делается дважды, один раз здесь, а второй на 62-й строчке в компоненте Ingredient. Все верно ты подмечал в том комментарии по поводу того, что если в стейте мы делаем объект, то в рендере придется делать преобразование в массив. Ответ на вопрос что лучше я не знаю, однако тот алгоритм обновления стейта на 25-28 строках получился намного красивее, понятнее и короче, чем в случае с массивом в стейте. Что по поводу этой строки (34) - можно улучшить немного, могу посоветовать вынести этот расчет в отдельную переменную, например isEnoughSelected или например limitReached и эту переменную подставить сюда, а также передать в Ingredient через пропсы. Получится сократить расходы в два раза

2022-05-20 15:34 UTC, AndrewHelix commented on src/Task-22.tsx
> +      {Object.values(selected).filter(el => el).length >= 5 && (
Так не получится сделать, потому что эта переменная вычислится один раз в родительском компоненте и передаст в каждый дочерний компонент одно значение. В таком случае, когда элементов будет выбрано 5, то все инпуты задезейблятся. Поэтому в дочернем компоненте для каждого нужно делать расчет дизейблед он или нет. ну или в фун-ии map на каждой итерации и прокидывать через пропсы. Но тут уже разницы нет, сути дела не меняет)

2022-05-20 15:36 UTC, merged