done task-26
AndrewHelix/react-homeworks pull request #14
Opened 2022-05-09 20:57 UTC by AndrewHelix

2022-05-10 14:55 UTC, PaulVersAtile commented
тип состояния для number инпута и range должны быть number

2022-05-16 10:14 UTC, PaulVersAtile commented on src/Task-26.tsx
> +    <input type="radio" name="radioInput" id='radioOne' value='Ded' checked={inputsState.radioInput === 'Ded' ? true : false} onChange={onChangeState}/>
Можно просто `checked={inputsState.radioInput === 'Ded'}`

2022-05-20 10:43 UTC, PaulVersAtile requested changes

2022-05-20 10:43 UTC, PaulVersAtile commented on src/Task-26.tsx
> +    value = e.target.type === 'number' || e.target.type === 'range' ? +value : value;
Тут ts кстати ругается ( установлен ли у тебя tslint ?) на 30-ю строчку. На 29-й value имеет автоматический вычисленный тип `boolean | string`, затем на 30-й тип может измениться на number - нехорошо. Я бы здесь какую-то функцию добавил, которая бы инкапсулировала эту возню с тернарниками отсюда и обозвал бы как-то вроде getValue, например. Но в целом ок, единственное только, надо стараться убирать все места на которые ругается TS линтер.

2022-05-20 10:43 UTC, PaulVersAtile commented on src/Task-26.tsx
> +    value = e.target.type === 'number' || e.target.type === 'range' ? +value : value;
Еще одно возможное решение, которое бы я мог предложить по поводу типизации этой функции - через generic
<img width="534" alt="Снимок экрана 2022-05-20 в 15 35 59" src="https://user-images.githubusercontent.com/103578069/169511433-f1703ba5-e143-4f3a-bfd0-7254a728ca71.png">
. Я также тут предложил фикс косяка, описанного в комменте выше, но лучше отдельную функцию)

2022-05-20 16:09 UTC, AndrewHelix commented on src/Task-26.tsx
> +    value = e.target.type === 'number' || e.target.type === 'range' ? +value : value;
Подправил, вынес в функцию. Но все же этот прикол, с тем, что подчеркивает ошибку (чекбокса нет у тексэрии). Так и не решил)
ТСлинт стоит и на 30ю строчку не ругался) Странно
![image](https://user-images.githubusercontent.com/78097819/169568490-f9fc6ea9-9364-49c3-afde-17c1fb093e44.png)

2022-05-20 16:12 UTC, AndrewHelix commented on src/Task-26.tsx
> +    value = e.target.type === 'number' || e.target.type === 'range' ? +value : value;
П.С. добавил копку, а в ТЗ она вроде как и не написана:)

2022-05-28 19:28 UTC, PaulVersAtile requested changes
Так ругаецца ж
<img width="886" alt="Снимок экрана 2022-05-28 в 22 27 26" src="https://user-images.githubusercontent.com/103578069/170840151-12cda943-ba11-45e6-9113-3449f6b7722e.png">
UPD: отмена, невнимательно прочитал твой вопрос в ПР

2022-05-28 19:33 UTC, PaulVersAtile commented on src/Task-26.tsx
> +    value = e.target.type === 'number' || e.target.type === 'range' ? +value : value;
В моем предложенном решении T экстендит типы, объединенные через `&` (и) - имитируя множественное наследование, т.е. грубо говоря в один большой объект собираются все проперти из перечисленных типов инпутов и получается такой тип якобы "универсального инпута". Тоже на самом деле не самое блистательное решение, но иначе придется уже тогда разделять эту функцию на три для каждого из типов инпутов. В твоем текущем решении сейчас HTMLElements - это выбор между одним из трех типов - они объединены через `|`. поэтому ts и ругается

2022-06-06 10:24 UTC, PaulVersAtile approved these changes

2022-06-19 13:57 UTC, merged